language: ruby
sudo: false
cache: bundler
rvm:
  - "2.0"
script: bundle exec rake
before_install:
  - gem update --system
  - gem update bundler
services:
  - redis-server
branches:
  except:
    - /^v[0-9]/
notifications:
  email: false
  webhooks:
    urls:
      - http://util.perceptes.com:8080/travis
